# Generated by Django 3.2.5 on 2021-08-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('email', models.TextField()),
                ('name', models.TextField()),
                ('contactNumber', models.TextField()),
                ('accountType', models.TextField()),
                ('bkash', models.IntegerField()),
                ('nagad', models.IntegerField()),
                ('bankAccount', models.IntegerField()),
                ('paymentMethodDetails', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotReceivedModel',
            fields=[
                ('buyId', models.IntegerField(primary_key=True, serialize=False)),
                ('sellId', models.IntegerField()),
                ('title', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('amount', models.TextField()),
                ('price', models.TextField()),
                ('full_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedModel',
            fields=[
                ('buyId', models.IntegerField(primary_key=True, serialize=False)),
                ('sellId', models.IntegerField()),
                ('title', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('amount', models.TextField()),
                ('price', models.TextField()),
                ('full_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SellModel',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('amount', models.TextField()),
                ('price', models.TextField()),
            ],
        ),
    ]
