# Generated by Django 3.2.5 on 2021-08-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='NotCollectedModel',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('amount', models.TextField()),
                ('price', models.TextField()),
            ],
        ),
    ]
