# Generated by Django 3.2.5 on 2021-08-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedModel',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('amount', models.TextField()),
                ('price', models.TextField()),
            ],
        ),
    ]
